### ISSUE TITLE
The code is not as expected

### ISSUE THREAD

**Issue by HAKO411** [suryaapratapp/Extracting-TripAdvisor-Reviews#1]
I try to run this code but I didn't receive any results.

**Comment by suryaapratapp** [comment]
Can you please let me know what error you're facing?

**Comment by HAKO411** [comment]
I run the code and this is the generated result. I don’t know what is wrong with it.

**Comment by suryaapratapp** [comment]
Your output would be a CSV file in the same directory of your code. (also make sure to pip install all the required imports)
Please attach the screenshot of the issue to make it more clear.
Thanks

**Comment by HAKO411** [comment]
This is the first two steps.

**Comment by HAKO411** [comment]
This is the last step and the result.

**Comment by suryaapratapp** [comment]
Hey, there is nothing attached to your messages! Can't see anything, I suggest you to take screenshot and attach an image file of your issue. (In the bottom of the message box there is _"Attach files by dragging and dropping button available. Please use this"_)
Thanks

**Comment by HAKO411** [comment]
Sorry I sent from my email and I though it would show.
<img width="1680" alt="Original" src="https://user-images.githubusercontent.com/61934483/83950074-49e31b00-a828-11ea-9065-3b6c4d540816.png">
<img width="1680" alt="start to run" src="https://user-images.githubusercontent.com/61934483/83950077-4e0f3880-a828-11ea-9c6d-4c8e03a62aad.png">
<img width="1680" alt="fisnished" src="https://user-images.githubusercontent.com/61934483/83950078-4ea7cf00-a828-11ea-817d-78c41130829f.png">
<img width="1537" alt="result" src="https://user-images.githubusercontent.com/61934483/83950080-4f406580-a828-11ea-9c90-df919354b4aa.png">

**Comment by suryaapratapp** [comment]
Hi there, 
I've made some changes in the code.
Can you please check it and update?
